# Generated by Django 2.1.1 on 2019-08-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255, null=True)),
                ('appname', models.CharField(max_length=255, null=True)),
                ('applogo', models.CharField(max_length=255, null=True)),
                ('fclassname', models.CharField(max_length=255, null=True)),
                ('kclassname', models.CharField(max_length=255, null=True)),
                ('usenum', models.CharField(max_length=255, null=True)),
                ('growth', models.CharField(max_length=255, null=True)),
                ('daymachinenum', models.CharField(max_length=255, null=True)),
                ('dmgrowth', models.CharField(max_length=255, null=True)),
                ('usetime', models.CharField(max_length=255, null=True)),
                ('timegrowth', models.CharField(max_length=255, null=True)),
                ('timename', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(default=0)),
                ('tuesday', models.IntegerField(default=0)),
                ('wednesday', models.IntegerField(default=0)),
                ('thursday', models.IntegerField(default=0)),
                ('friday', models.IntegerField(default=0)),
                ('saturday', models.IntegerField(default=0)),
                ('sunday', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='spider_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=255, null=True)),
                ('interval_time', models.CharField(max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
