# Generated by Django 2.1.1 on 2019-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_count',
            name='last_week',
            field=models.IntegerField(default=0),
        ),
    ]
