# Generated by Django 2.1.1 on 2019-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0002_data_count_last_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_count',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='data_count',
            name='last_week',
        ),
        migrations.RemoveField(
            model_name='data_count',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='data_count',
            name='sunday',
        ),
        migrations.AddField(
            model_name='data_count',
            name='database_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
