# Generated by Django 2.1.1 on 2019-08-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0003_auto_20190803_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_count',
            name='database_name',
            field=models.CharField(max_length=255),
        ),
    ]
