# Generated by Django 2.1.1 on 2019-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0004_auto_20190803_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_count',
            name='friday',
            field=models.IntegerField(default=0),
        ),
    ]
